SRC_REPO_BASE_URL='https://src.fedoraproject.org/rpms'
MOCK_CHROOT_CFG='fedora-37-riscv64'
PKG_REPO_BRANCH='rawhide'
REPO_SRPM_PATH='/mnt/nfs/data-exchange/http-shared/perl-bootstrap/src/Packages/'
REPO_RPM_PATH='/mnt/nfs/data-exchange/http-shared/perl-bootstrap/riscv64/Packages/'
MOCK_CUSTOM_ENV_VER='plct'
